### ISSUE TITLE
Remove on hover div

### ISSUE THREAD

**Issue by andreskeeled** [getstation/desktop-app-releases#11]
The gigantic on hover div that shows every time I want to go to another service is cringing. It's not really that useful and not the best user experience. It would be nice to have the on/off option for that on hover. 

Cheers guys

**Comment by MathieuDebit** [comment]
Hello 👋

The actual implementation of the Subdock, as we call it, is indeed an issue for some users, and we are actively working on it.
See this community thread: [The subdock is too big / side-panel is annoying / hover menu is frustrating](https://community.getstation.com/t/the-subdock-is-too-big-side-panel-is-annoying-hover-menu-is-frustrating/162/23).

https://community.getstation.com is the place where we gather all requests and handle bug reports. Feel free to open a new topic there if you need anything, this repo is only used for publishing releases.

Thanks 🙏
