### ISSUE TITLE
Missing time

### ISSUE THREAD

**Issue by PeterDraex** [getstation/desktop-app-releases#12]
Hello,
I'd love to work in fullscreen mode with station, but I really miss seeing time. I check it often while working. Could you perhaps add it as an optional widget?

Thanks,
Peter

**Comment by alexstrat** [comment]
👋
That's a good idea!
Please use the community (https://community.getstation.com/) to report feature ides. If you are able to find an existing thread about a similar ideas by searching in community, you can upvote directly.
Thank you! 👍
