### ISSUE TITLE
Office 365 Outlook link opens in browser

### ISSUE THREAD

**Issue by albertvolkman** [getstation/desktop-app-releases#14]
The other links appear to work, but the Outlook one always opens in default browser.

**Comment by alexstrat** [comment]
👋
Please use the community (https://community.getstation.com/) to report issues. If you were able to find your issue by searching in community, you can upvote directly.
Thank you! 👍

**Comment by albertvolkman** [comment]
https://community.getstation.com/t/office-365-outlook/1440

Done.
