### ISSUE TITLE
Trello not able to load resources.

### ISSUE THREAD

**Issue by parsgeo** [getstation/desktop-app-releases#15]
The Trello app is displaying the following text on startup of Station:

> Your browser was unable to load all of Trello's resources. They may have been blocked by your firewall, proxy or browser configuration.
> 
> Try refreshing the page and if that doesn't work, check out our troubleshooting guide.

Running windows 10

I followed the Trello troubleshooting guide on the displayed page. Which just tells you to allow trellos CDN through the firewall. I also just turned off the firewall. That also did not work. 

I believe it is an issue with browserX.

**Comment by oskarmar** [comment]
Same Issue.
I removed completely Station (searching in appdata) and reinstalled but the issue continues.
In my same network there is another computer with station installed and it works fine there.

**Comment by alexstrat** [comment]
👋
Please use the community (https://community.getstation.com/) to report issues. If you were able to find your issue by searching in community, you can upvote directly.
