### ISSUE TITLE
Issues with Asana loading and login

### ISSUE THREAD

**Issue by nsudds** [getstation/desktop-app-releases#16]
Several people including myself are having issues with Asana loading and login on desktop. 

Could you please review and maybe this is a better way to provide the log files etc as the support via the forums doesn't seem to be making progress. 

Here's a link to more descriptions on the issues
https://community.getstation.com/t/asana-doesnt-load/1738
https://community.getstation.com/t/asana-log-in-with-google-failed/990

I also sent a tweet to get attention but then didn't get a reply so decided to check for the project on Github
https://twitter.com/NathanSudds/status/981062220581752833

Hope this helps get it resolved and help others who've been reporting issues too. 

Thanks!

**Comment by alexstrat** [comment]
Thanks for the heads up. This should be fixed in the latest version of Station.
Let's continue the discussion in the community if necessary.
