### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by alenguav** [getstation/desktop-app-releases#17]
Don't know what happened but my Station installation in Windows 10 is currently becoming so slow that it is freezing

**Comment by nwdfusion** [comment]
The station app is freezing seriously since the new update, I cant seamlessly switch between apps like before.  I'm using a 1 month old Macbook pro 2015

**Comment by MathieuDebit** [comment]
Hi,

https://community.getstation.com is the place where we gather all requests and handle bug reports. Feel free to open a new topic there if you need anything, this repo is only used for publishing releases.
