### ISSUE TITLE
Slack app blank

### ISSUE THREAD

**Issue by bewhari** [getstation/desktop-app-releases#18]
App version: 1.11.2
Operating system: OSX 10.12.6 
Description: Slack apps seem to not be displaying the sidebar and content correctly. Both are now blank. I've attached a screenshot below.

![screen shot 2018-05-07 at 8 46 06 am](https://user-images.githubusercontent.com/6384159/39705442-082f3786-51d4-11e8-8998-cec1c6639dbd.png)

**Comment by MathieuDebit** [comment]
I'm closing this issue, if you need anything feel free to visit https://community.getstation.com. Thanks 🙏
