### ISSUE TITLE
Issue on Japanese Input on using Slack

### ISSUE THREAD

**Issue by pco2699** [getstation/desktop-app-releases#20]
Hi, thanks for making Station. This app is very useful and I love this app.

But, when I input Japanese on Slack, sometimes unexpected space is mixed to text.
I think this issue is same with these issues. (But, it was already fixed.)
https://github.com/electron/electron/issues/9173#issuecomment-296808208

It would be very helpful if you can fix this issue in Station.

**Comment by MathieuDebit** [comment]
Hi @pco2699 (sorry for the delay 🙈),

https://community.getstation.com is the place where we gather all requests and handle bug reports. Feel free to open a new topic there if you need anything, this repo is only used for publishing releases.
