### ISSUE TITLE
Wrike Integration Broken

### ISSUE THREAD

**Issue by xHeinrich** [getstation/desktop-app-releases#21]
It appears that the wrike integration is broken.

![image](https://user-images.githubusercontent.com/7674587/43756078-6f82b6d6-9a56-11e8-8b45-643bfea433e8.png)

**Comment by MathieuDebit** [comment]
Hi @xHeinrich (sorry for the delay 🙈),

https://community.getstation.com is the place where we gather all requests and handle bug reports. Feel free to open a new topic there if you need anything, this repo is only used for publishing releases.
