### ISSUE TITLE
Source zip and tar.gz only contain README.md

### ISSUE THREAD

**Issue by robpetrin** [getstation/desktop-app-releases#23]
Hi guys -- I love your product and use it religiously on Windows. I currently cannot install AppImage files (Chrome OS Crostini, and AppImages don't play nice with containers), so I'd like to install from source. It seems that both archived versions of the source package are just an empty archive besides the README.md file.

Am I missing something? Thanks!

**Comment by MathieuDebit** [comment]
Hi @robpetrin 👋 

Thanks for your feedback. As Station isn't an open-source project, we don't share the codebase publicly (we might consider changing this at some point), and this repo is only used as an update server (we only add compiled sources).

We're happy that Station suits you on Windows! Linux support took us some time to handle and we prioritise our efforts to the most requested features, so unfortunately we can't guarantee you any ChromeOS support.

Fell free to open a topic on https://community.getstation.com, this is where we gather all requests and handle bug reports, other users might have the same need!

Thanks!
