### ISSUE TITLE
Dropbox paper keeps showing popup window

### ISSUE THREAD

**Issue by pranavpanchal** [getstation/desktop-app-releases#24]
Whenever I open up dropbox paper and go into a document, the following popup (image linked below) comes up. Whenever I try to close it, it just reappears. It only closes when I exit any document. Not sure what the problem is.

<img width="1206" alt="screen shot 2018-09-26 at 10 51 25 pm" src="https://user-images.githubusercontent.com/17016563/46121015-e3e36b00-c1df-11e8-86fa-efe7eb60d150.png">

**Comment by MathieuDebit** [comment]
👉https://community.getstation.com/t/dropbox-paper-keeps-showing-popup-window/4128
