### ISSUE TITLE
too slow service in windows

### ISSUE THREAD

**Issue by Lvaskz** [getstation/desktop-app-releases#26]
Hi, I am using windos 7 pro.
64 bit
 The aplication is too mucho slow, gmail never loades its too much anoying.
help ?

**Comment by MathieuDebit** [comment]
Hello @Lvaskz 👋

https://community.getstation.com is the place where we gather all requests and handle bug reports. Feel free to open a new topic there if you need anything, this repo is only used for publishing releases.
