### ISSUE TITLE
Make the back button function on a mouse when in gmail

### ISSUE THREAD

**Issue by sigginet** [getstation/desktop-app-releases#27]
One of the most annoying things is when I'm trying to go through today's 300 emails.
In chrome I've used the back button to go out of an email, retain my mouse position and then click on the next email.

Now I can't since using station, so it slows me down significantly when going through e-mails.

Can you enable the back button on the mouse to allow us to go to the previous page?

**Comment by MathieuDebit** [comment]
Hi @sigginet 👋

Thanks for your feedback!
https://community.getstation.com is the place where we gather all requests and handle bug reports. Feel free to open a new topic there if you need anything, this repo is only used for publishing releases.
