### ISSUE TITLE
Can't get through 2FA for Google services

### ISSUE THREAD

**Issue by danielrosehilljlm** [getstation/desktop-app-releases#31]

**Comment by danielrosehilljlm** [comment]
Trying to add Google services secured with 2FA and 2FA options menu does not populate; progress bar cycles repetitively:

https://imgur.com/a/qC7FFv0

**Comment by magne4000** [comment]
@danielrosehilljlm sorry for the long reply time, our main feature and bug request page is here: https://feedback.getstation.com
Nevertheless, do you still experience the issue you described ?
