### ISSUE TITLE
Minimized main window

### ISSUE THREAD

**Issue by juanjotoronja** [getstation/desktop-app-releases#32]
It doesn't let me pull a request so here are some features to be considered:

-Minimize to system tray (as an option in settings)
-Close to system tray (avoids accidentally closing the app)
-Pressing ESC key sends to system tray (shortcut)
-Start minimized/Send to system tray on startup (some electron apps has this implemented)

I really like the simplicity and the History back/forward shortcuts, keep it up guys :)

**Comment by utajum** [comment]
+1

**Comment by magne4000** [comment]
@juanjotoronja thanks for you support and your ideas!
@utajum thanks for pointing to the Feature Request page. I'm closing this in favour of the Canny page.
