### ISSUE TITLE
aide creation docker

### ISSUE THREAD

**Issue by oda-alexandre** [getstation/desktop-app-releases#33]
Bonjour et merci pour votre travail.

Je souhaiterais vous demander s'il est possible de m'aider a améliorer mon docker de getstation https://github.com/oda-alexandre/getstation vous avez le lien vers le docker hub public du projet dans le README.

Je souhaiterai si celui-ci vous satisfait vous demander s'il est possible de l'intégré a votre projet.

Merci pour votre retour et encore merci pour votre travail.

**Comment by magne4000** [comment]
Bonjour @oda-alexandre et merci pour l'intérêt porté à Station !

Le support d'une image Docker est une très bonne idée, mais nous n'avons pas les resources pour assurer son support. Je préfère donc que son support reste assuré par la communauté.

Ceci étant dit, nous allons sortir une version 2.0 dans quelques semaines, et nous arrêtons l'ajout de fonctionnalités pour la v1 par la meme occasion.

**Comment by oda-alexandre** [comment]
merci de votre retour
