### ISSUE TITLE
Notifications issue on Gmail accounts

### ISSUE THREAD

**Issue by SirLouen** [getstation/desktop-app-releases#34]
After inserting a new Gmail account, notifications are not show my default
One must click once in the "disable notification" in the account, in order to activate them. 
This must be a UI bug reported already here:
https://feedback.getstation.com/bugs-support/p/notification-are-not-working-are-inconsistent-no-red-dots-activity-badgeson-the

Little example to show this behaviour (only happens the first time once created, for each account):

![gmail bug](https://media.giphy.com/media/ic6yVWXti0R98OymtT/giphy.gif)

**Comment by magne4000** [comment]
Thanks for your feedback.

We are soon releasing a complete rework of the Station experience, so in the mean time, the support on the current version is limited due to limited resources. Stay tuned for the 2.0 release in few weeks!
