### ISSUE TITLE
[REQUEST] Snap package?

### ISSUE THREAD

**Issue by i-am-ecc** [getstation/desktop-app-releases#37]
Are there any plans to make Station also available as Snap package, along with AppImage? Many people would like to install and update it this way, I guess.

**Comment by magne4000** [comment]
Hello @i-am-ecc 
We are currently in the process of releasing a complete rework of Station under a 2.0 version.
As we have a limited dev team, the current version (1.0) will not receive any new features, so we will not be able to add support for Snap builds.

Stay tuned for the 2.0 release!
