### ISSUE TITLE
google apps in single window

### ISSUE THREAD

**Issue by ngoyal16** [getstation/desktop-app-releases#38]
Can't we have single widnow which will allow to have all other google apps like chat, meet, drive, docs. we can use diffrent tabs in single window

same way Atlassain products.

**Comment by magne4000** [comment]
Hello @ngoyal16 
We are currently in the process of releasing a complete rework of Station under a 2.0 version.
As we have a limited dev team, the current version (1.0) will not receive any new features.

Stay tuned for the 2.0 release!

**Comment by ngoyal16** [comment]
@magne4000 if you need help in development I can help..

BTW can you estimate how much long it gonna take for 2.x release
