### ISSUE TITLE
workspaces

### ISSUE THREAD

**Issue by ngoyal16** [getstation/desktop-app-releases#40]
Hello Team,

As a consultant i manages lots of clients accounts. gmail, aws and other stuff. is there a possible way we can have workspace feature. where each workspace has its own set of application running on. 

2 workspace should not share cookies with each other

**Comment by magne4000** [comment]
Hello @ngoyal16 
We are currently in the process of releasing a complete rework of Station under a 2.0 version.
As we have a limited dev team, the current version (1.0) will not receive any new features.

Stay tuned for the 2.0 release!
