### ISSUE TITLE
Improve Bookmarking experience

### ISSUE THREAD

**Issue by jedlikowski** [getstation/desktop-app-releases#5]
Hi,
thanks for the great app!

I've just started using bookmarks in Station and noticed that it doesn't always work for all apps. Some of them don't allow you to click a link and open it in new window to force this new window to appear in the side dock and be "bookmarkable". This happens in inVision and Google Drive. You can't CMD+click on a directory in GDrive to open it in new window. 

It would be great to have a menu item called "bookmark this page", for example under "view" in the main app menu. What do you think about this?

**Comment by magne4000** [comment]
Thanks @jedlikowski for your feedback!
If you have not already, you can join the [Community](https://community.getstation.com/) to discuss this subject. We are still searching for a better way to handles those bookmarks, and every suggestion is welcome !
But definitely, a `Bookmark this page` button would at least make your use case easier.
