### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by ohhdear** [getstation/desktop-app-releases#6]
Thanks for building Station, I really like it. Unfortunately, it no longer opens correctly. I'll go ahead and uninstall and reinstall and see if that works, but I figured I'd post the fatal error here, just in case you want to have it and for future people of the internet to use.

```
The saved Station state is not compatible with the current Station version.
executedSet: 01-applicationId-null-not-allow.js, 20171211120843-app-installation-limit.js, 20171220180516-add-user-weekly-usage-table.js, 20170901161612-add-column-tooltip.js, 201708301820-add-user-picture.js, 20171212145600-add-column-onboarding-teammates.js, 20180130123653-remove-referral-tooltip-columns.js, 20170825181500-add-column-sleep-notif.js, 201712180000-add-ui-bis.js, 201708211718-add-organizations.js, 00-schema-creation.js, 201707211543-pk-null-not-allow.js, 01-add-subwindows.js, 201712061725-add-ui.js
allSet: 01-applicationId-null-not-allow.js, 20171211120843-app-installation-limit.js, 20171220180516-add-user-weekly-usage-table.js, 20170901161612-add-column-tooltip.js, 201708301820-add-user-picture.js, 20171212145600-add-column-onboarding-teammates.js, 20170825181500-add-column-sleep-notif.js, 201712180000-add-ui-bis.js, 201708211718-add-organizations.js, 00-schema-creation.js, 201707211543-pk-null-not-allow.js, 01-add-subwindows.js, 201712061725-add-ui.js
UnknownSets: 20180130123653-remove-referral-tooltip-columns.js
```

**Comment by magne4000** [comment]
Hello @ohhdear, this can happen if you tried to install an older version of Station at some point.
This means the data scheme is not compatible with the version you are currently trying to launch.

Do you have multiple versions of Station installed on your machine ? Or did you try to rollback to some older version at some point ? Also, what is the version of Station with which you have this error ?

To fix the issue, you can try to download station again and reinstall it.

Thanks for the report 😉
