### ISSUE TITLE
iTunes Connect frequently fails with 401 Unauthorized

### ISSUE THREAD

**Issue by diakonos** [getstation/desktop-app-releases#7]
Since the last update I've found that quite frequently--every day or so--iTunes Connect will fail with a 401 Unauthorized error. All I can see is a white page with the following message:

> Unauthenticated Request ID: {some request id}

It seems to be attempting to directly navigate to one of my apps on iTunes Connect, but I guess the authentication has expired. Refreshing doesn't fix it, and I can't seem to find a way to "reset" the app either, so I have to manually remove and re-add the app.

System info:
13-inch 2016 MacBook Pro
macOS High Sierra
Station 1.4.1

**Comment by alexstrat** [comment]
👋
Please use the community (https://community.getstation.com/) to report issues. If you were able to find your issue by searching in community, you can upvote directly.
Thank you! 👍
