### ISSUE TITLE
Developer API - make custom Station apps

### ISSUE THREAD

**Issue by AkdM** [getstation/desktop-app-releases#9]
Hey there (from Paris too!),

I would be awesome to have some sort of developer API to make custom and/or private applications.
In the company I work for, we are developing a platform. This platform is private for our clients only.

Is it something you're planning or not at all? :)

Thanks!

(oh also, in the meantime, please support Hipchat Enterprise,mostly for custom domains 🙄)

**Comment by alexstrat** [comment]
Hi @AkdM,

We are adding custom/private/on-premise applications for teams, you might be interested. The API is not ready though for this use-case, but that's definitely in the natural continuation.

We are reaching directly to you by email for the team's applications!
